Avoid recursive python3_sitearch expansion even if undefined
Fixes an error during SRPM construction if not enough dependencies
are installed (e.g., during the first build stage in mock):

error: /builddir/build/SPECS/samba.spec: line 2478: Too many levels
  of recursion in macro expansion. It is likely caused by recursive
  macro declaration.